# -*- coding: utf-8 -*-
"""01_인공지능스피커_TTS(튜터용).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CjQPVWvCJYBVTfDNkWiGn8G_1ro54dyD
"""

pip install click==8.2.1

pip install gtts --no-deps

!pip install gTTS

from gtts import gTTS

#  영어문장 사운드 파일 생성 및 저장
text = '안녕하세요 인공지능 스피커'
file_name = 'sample.mp3'
tts_en = gTTS(text=text, lang='ko')
tts_en.save(file_name)

"""3) 코랩 환경에서 .mp3 파일 재생"""

#  코랩 환경에서 .mp3 파일 재생
from IPython.display import Audio
sound = Audio(file_name, autoplay=True)

from IPython.display import Audio, display
sound = display(Audio(file_name, autoplay=True))

"""1) SpeechRecongintion(음성인식) 패키지 설치"""

!pip install SpeechRecognition

"""2) mp3 파일을 .wav 로 변환하기"""

!pip install pydub

from pydub import AudioSegment

mp3_file = 'sample.mp3'
wav_file = 'sample.wav'

sound = AudioSegment.from_mp3(mp3_file)
sound.export(wav_file, format='wav', parameters=['-ac','1','-ar','16000'])

import speech_recognition as sr
# 음성인식 객체 생성
recognizer = sr.Recognizer()
# 오디오 파일 로드
audio_file = 'sample.wav'

with sr.AudioFile(audio_file) as source:
  print("음성을 인식 중입니다....")
  audio_data = recognizer.record(source)

text = recognizer.recognize_google(audio_data, language='ko')
print("변환된 텍스트:",text)

"""4) 실시간"""

import speech_recognition as sr

# 음성인식 객체 생성
recognizer = sr.Recognizer()
